### ISSUE TITLE
Access to spoons

### ISSUE THREAD

**Issue by Grazfather** [agzam/spacehammer#100]
`spoon` is not accessible in the _config.fnl_ namespace.

Using `hs.loadSpoon` works, but still does not properly put `spoon` in the namespace.

It seems that I can fix this by calling `loadSpoon` from _init.lua_, but that requires making an edit in this repo, while it would be better if I didn't have to make changes there.

Could we maybe do something in _init.lua_ to export `spoon` so that _config.fnl_ has access without any hacks?

**Comment by agzam** [comment]
I have not played with spoons. At some point I'll try them out. Thank you for the idea.

**Comment by Grazfather** [comment]
Great. I reported a bug to hammerspoon/hammerspoon#2912 which makes `hs.loadSpoon("")` not work, but otherwise a simple 'nop' spoon could be created, maybe, that at least puts `spoon` in the namespace, otherwise I can't use spoons and spacehammer together without using my own fork.

**Comment by eccentric-j** [comment]
Fixed by #123

**Comment by eccentric-j** [comment]
As far as I understand the `spoon` global is not created until a spoon is loaded. So if you update `init.lua` and load a spoon, then fennel will bind the `spoon` global when it's initialized. Otherwise it seems lua globals are not automatically available in fennel if created after fennel initializes.
