### ISSUE TITLE
feature request: Declarative approach

### ISSUE THREAD

**Issue by agzam** [agzam/spacehammer#18]
Perhaps it'd be nice if a user can configure keybindings, add/remove modules from a single location, maybe a .json file, I don't know.

**Comment by eccentric-j** [comment]
I would like to propose #20 to solve this problem. It looks for `~/.hammerspoon/private/config.fnl` (custom) or `~/.hammerspoon/config.fnl` (default). 

Went with fennel for the config because it allows users to define inline functions. A perfectionist can split it out into separate files and compose it together in their config.fnl while someone who just wants to get something done can write one-off functions for their custom menus or bindings in their single config file.

Additionally, you could use `config.fnl` as an entry point for behavior customizations as well for instance performing some kind of io or listeners to dynamically change menus.

**Comment by agzam** [comment]
fixed in 1.5
