### ISSUE TITLE
When switching windows quickly, the yellow outline gets left behind

### ISSUE THREAD

**Issue by tntmarket** [agzam/spacehammer#46]
**To Reproduce:** 

Switch back and forth between windows quickly
Video: https://gfycat.com/officialsnivelingemperorpenguin

**Result:** The yellow outline when switching focus stays, even after closing or moving the window

**Workaround:** Reload config in hammerspoon

**My Computer:**
Mac Version: 10.15.4
Hammerspoon Version: [0.9.78]
Spacehammer Version: 9c996802b5329df3e9f3d612a1e71a46395a0be0

**Potential Duplicate:** https://github.com/agzam/spacehammer/issues/9

**Comment by eccentric-j** [comment]
Confirming error reproduction.

Current hypothesis:
While not seemingly related to #9 it seems to mirror #31 where after many, rapid uses it seems to stop working. The cause was the garbage collector cleaning up refs to the listeners that were not stored anywhere.

Possible fixes:
- Create a shared ref to the rectangle object the jump function sets so that there will never be more than 1 highlighted window and timer to clean up.
- Create a queue or stream of these events to clean up. May require an FRP stream library I'm drafting for fennel.

I'm going to give solution #1 a shot as that will be much faster to draft and test. Thanks for the detailed report.

**Comment by agzam** [comment]
@tntmarket Thank you for reporting it, and thank you @eccentric-j for addressing it so quickly. I am sorry folks for being very slow at approving and reviewing things. My team got furloughed due to COVID-19 crisis, and the job search occupies most of my time lately. I approved the PR and I hope we can merge the fix soon.
