### ISSUE TITLE
toggle app?

### ISSUE THREAD

**Issue by dxuehu** [agzam/spacehammer#52]
how might I be able to write a toggle-app fn? specifically, I'd like cmd+k to show the kitty app if it's not the current screen, else hide it. I'm trying to reproduce something like https://github.com/kovidgoyal/kitty/issues/45#issuecomment-573196169 but I'm using spacehammer :) I'd appreciate any pointers. Thanks!

I have
```
(fn toggle-app
  [app-name]
  (hs.application.launchOrFocus app-name)
  (let [app (hs.application.find app-name)]
    (when app
      (if (: app :isFrontmost)
        (: app :hide)
        (
          (: app :activate) ;; not sure if I need both
          (: app :unhide))))))

(fn toggler
  [app-name]
  (fn toggle []
    (toggle-app app-name)))

;; in common-keys
{:mods [:cmd]
         :key :k
         :repeatable false
         :action (toggler "Kitty")}
```
the window flashes- seems to activate then hide immediately- when I press cmd+k.

**Comment by eccentric-j** [comment]
That's not far off! I tried it out and was able to get it working.

```fennel
(fn toggle-app
  [app-name]
  (let [app (hs.application.find app-name)]
    (if (and app (: app :isFrontmost))
        (: app :hide)
        (do
          (hs.application.launchOrFocus app-name)
          (: app :unhide)))))

(fn toggler
  [app-name]
  (fn toggle []
    (toggle-app app-name)))

```

- The toggle-app function was calling launchOrFocus at the beginning of the function meaning `(app:isFrontmost)` will always return true. I fixed by moving the call into the failing branch of the if statement.
- The this argument to your if statement `(   (: app :activate) (: app :unhide))` is a bit off.
- An assumption on my part is that if the app is not running you would like to open it. I simplified the nested conditionals so that we can treat when the app is not the frontmost or not running the same.
- If you're using the latest version of fennel you can write `(app:active)` or `(app:isFrontmost)` instead of the `(: app :isFrontmost)`. Interestingly, we did not have that option when we started the project.

I hope this helps.

**Comment by dxuehu** [comment]
Ahh that makes sense. Cool, I have no idea what I'm doing here (don't know any lisp or lua), just trying to reverse engineer :)

That works perfectly, thanks so much!!

**Comment by eccentric-j** [comment]
You're welcome! You took the important steps of trying it yourself and learned a bit of lua\lisp along the way. That's what's important 🚀
