### ISSUE TITLE
Modal for VIM keybindings

### ISSUE THREAD

**Issue by ananthhh** [agzam/spacehammer#6]
I love this product. Thanks for building this!

It will be great if there is a new mode with basic VIM normal mode keybindings. 
Let's call it VIM mode.
Once user is in this mode, we can initially have 'hjkl' mapped to respective arrow keys. 
For Example, If I press 'h' key when this mode is enabled, right arrow key should be triggered.

After 'hjkl' we can add more bindings.

I will work on this mode and send a pull request if you are ok with this idea.

**Comment by agzam** [comment]
Indeed, Vi-mode would be great. Personally I'm currently using Karbiner, so I wouldn't probably use this feature very often. Unfortunately, Karabiner is not compatible with Sierra, and I don't know how soon Karabiner Elements (rewrite of Karabiner) will have all the features I need - I still haven't upgraded to Sierra, simply because I'm scared to lose all the nice stuff that Karabiner offers. But sooner or later I will have to upgrade.

Related #7

**Comment by ananthhh** [comment]
@agzam 
Initially I was using karabinar as well. IMO OS updates were more important than losing key bindings as I can't compromise on security. Sierra also has some cool features like continuity and storage optimization.
